apiVersion: v1
kind: Service
metadata:
  name: k8s-lens-dashboard
  namespace: k8s-lens
  labels:
    app: k8s-lens
    component: dashboard
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: k8s-lens
    component: dashboard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-lens-service-account
  namespace: k8s-lens